name: bayesian
channels:
  - defaults
dependencies:
  - pip=20.0.2
  - python=3.7
  - setuptools=47.1.1
  - pip:
    - hyperopt==0.2.5
    - pomegranate==0.14.4
    - pymc3==3.8
    - numpy==1.20.2
    - bnlearn==0.3.17
    - pandas==1.2.4
    - matplotlib==3.4.1
    - scikit-learn==0.22.1
    - networkx>=2.0
    - scipy>=0.17.0
