name: bayesian
channels:
  - defaults
dependencies:
  - numpy
  - pandas
  - pip=20.0.2
  - scikit-learn=0.22.1
  - scipy
  - setuptools=47.1.1
  - pip:
    - cython==0.29.19
    - gpy==1.9.9
    - gpyopt==1.2.6
    - hyperopt==0.2.4
    - pystan==2.19.1.1
    - pymc3